/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <time.h> 
#include <string.h>
#include <sys/utsname.h>
#include "isaMIB.h"

#define LOGIN_LEN 8
#define TIME_STR_LEN 28
#define OS_STR_LEN 255

static char loginObject[LOGIN_LEN] = "xholko02";
static char currentTimeObject[TIME_STR_LEN];
static int numberObject = 42;
static int numberObject_backup;
static char operatingSystemObject[OS_STR_LEN];

/** Initializes the isaMIB module */
void
init_isaMIB(void)
{
    const oid loginObject_oid[] = { 1,3,6,1,3,22,1 };
    const oid currentTimeObject_oid[] = { 1,3,6,1,3,22,2 };
    const oid numberObject_oid[] = { 1,3,6,1,3,22,3 };
    const oid operatingSystemObject_oid[] = { 1,3,6,1,3,22,4 };

  DEBUGMSGTL(("isaMIB", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("loginObject", handle_loginObject,
                               loginObject_oid, OID_LENGTH(loginObject_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("currentTimeObject", handle_currentTimeObject,
                               currentTimeObject_oid, OID_LENGTH(currentTimeObject_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("numberObject", handle_numberObject,
                               numberObject_oid, OID_LENGTH(numberObject_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("operatingSystemObject", handle_operatingSystemObject,
                               operatingSystemObject_oid, OID_LENGTH(operatingSystemObject_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_loginObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     &loginObject,/* XXX: a pointer to the scalar's data */
                                     sizeof(char)*LOGIN_LEN);/* XXX: the length of the data in bytes */
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_loginObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_currentTimeObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    time_t t = time(NULL);
    struct tm lt = {0};
    localtime_r(&t, &lt);
    size_t len = strftime(currentTimeObject, TIME_STR_LEN, "%Y-%m-%dT%H:%M:%S%z", &lt);
    char minute[] = { currentTimeObject[len-2], currentTimeObject[len-1], '\0' };
    sprintf(currentTimeObject + len - 2, ":%s", minute);

    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     &currentTimeObject,/* XXX: a pointer to the scalar's data */
                                     sizeof(char)*TIME_STR_LEN);/* XXX: the length of the data in bytes */
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_currentTimeObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_numberObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     &numberObject, /* XXX: a pointer to the scalar's data */
                                     sizeof(numberObject)); /* XXX: the length of the data in bytes */
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            numberObject_backup = numberObject;
            //if (/* XXX if malloc, or whatever, failed: */) {
            //    netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            //}
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            /* XXX: perform the value change here */
            numberObject = *(requests->requestvb->val.integer);
            //if (/* XXX: error? */) {
            //    netsnmp_set_request_error(reqinfo, requests, /* some error */);
            //}
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            //if (/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
            //    netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            //}
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            numberObject = numberObject_backup;
            //if (/* XXX: error? */) {
                /* try _really_really_ hard to never get to this point */
            //    netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            //}
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_numberObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_operatingSystemObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    struct utsname name;
    if (uname(&name)) {
        // TODO - error if non-0 return
    }  
	//printf("Your computer's OS is %s@%s\n", name.sysname, name.release);
    strncpy(operatingSystemObject, name.sysname, sizeof(name.sysname));

    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     &operatingSystemObject,/* XXX: a pointer to the scalar's data */
                                     sizeof(char)*OS_STR_LEN);/* XXX: the length of the data in bytes */
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_operatingSystemObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
