/**
 * @file isaMIB.c
 * @author Natalia Holkova (xholko02), FIT
 * @date 18.11.2020
 *
 * Project for ISA, task variant - SNMP agent extension
 * 
 * Note: this file originally auto-generated by mib2c using
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <time.h> 
#include <string.h>
#include <sys/utsname.h>
#include "isaMIB.h"

#define LOGIN_LEN 8
#define TIME_STR_LEN 25
#define OS_STR_LEN 255

static char loginObject[LOGIN_LEN] = "xholko02";
static char currentTimeObject[TIME_STR_LEN];
static int numberObject = 42;
static int numberObject_backup;
static char operatingSystemObject[OS_STR_LEN];

/**
 * Initializes the isaMIB module
 */
void init_isaMIB(void) {
    const oid loginObject_oid[] = { 1,3,6,1,3,22,1 };
    const oid currentTimeObject_oid[] = { 1,3,6,1,3,22,2 };
    const oid numberObject_oid[] = { 1,3,6,1,3,22,3 };
    const oid operatingSystemObject_oid[] = { 1,3,6,1,3,22,4 };

  DEBUGMSGTL(("isaMIB", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("loginObject", handle_loginObject,
                               loginObject_oid, OID_LENGTH(loginObject_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("currentTimeObject", handle_currentTimeObject,
                               currentTimeObject_oid, OID_LENGTH(currentTimeObject_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("numberObject", handle_numberObject,
                               numberObject_oid, OID_LENGTH(numberObject_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("operatingSystemObject", handle_operatingSystemObject,
                               operatingSystemObject_oid, OID_LENGTH(operatingSystemObject_oid),
                               HANDLER_CAN_RONLY
        ));
}

/**
 * loginObject handling
 */
int handle_loginObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests) {
    
    switch(reqinfo->mode) {

        case MODE_GET:
            // get value
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     &loginObject, // a pointer to the scalar's data
                                     sizeof(char)*LOGIN_LEN); // the length of the data in bytes
            break;


        default:
            // we should never get here - a really bad error
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_loginObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

/**
 * currentTimeObject handling 
 */
int handle_currentTimeObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests) {

     /********************************************************************************
      * Disclaimer: getting utc time was inspired by 
      * https://stackoverflow.com/questions/13804095/get-the-time-zone-gmt-offset-in-c
      ********************************************************************************/
    time_t t = time(NULL);
    struct tm lt = {0};
    localtime_r(&t, &lt);
    size_t len = strftime(currentTimeObject, TIME_STR_LEN, "%Y-%m-%dT%H:%M:%S%z", &lt);
    char minute[] = { currentTimeObject[len-2], currentTimeObject[len-1], '\0' };
    sprintf(currentTimeObject + len - 2 , ":%s", minute);

    switch(reqinfo->mode) {

        case MODE_GET:
            // get value
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     &currentTimeObject, // a pointer to the scalar's data
                                     sizeof(char)*TIME_STR_LEN); // the length of the data in bytes
            break;


        default:
            // we should never get here - a really bad error
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_currentTimeObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

/**
 * numberObject handling
 */
int handle_numberObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests) {
    int ret;
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     &numberObject, // a pointer to the scalar's data 
                                     sizeof(numberObject)); // the length of the data in bytes
            break;

        // SET REQUEST
        case MODE_SET_RESERVE1:
            // try to detect invalid SET requests as soon as possible
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            numberObject_backup = numberObject;
            break;

        case MODE_SET_FREE:
            // free resources allocated in RESERVE1 and/or RESERVE2 - not needed
            break;

        case MODE_SET_ACTION:
            // perform the value change here
            numberObject = *(requests->requestvb->val.integer);
            break;

        case MODE_SET_COMMIT:
            // delete temporary storage - not needed
            break;

        case MODE_SET_UNDO:
            // UNDO and return to previous value for the object */
            numberObject = numberObject_backup;
            break;

        default:
            // we should never get here - a really bad error
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_numberObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

/**
 * operatingSystemObject handling
 */
int handle_operatingSystemObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests) {
    
    struct utsname name;
    if (uname(&name)) {
        // error - could not get system name
        strncpy(operatingSystemObject, "System name could not be detected", sizeof("System name could not be detected"));
    }  
    else {
        // system name successfully detected
        strncpy(operatingSystemObject, name.sysname, sizeof(name.sysname));
    }

    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     &operatingSystemObject, // a pointer to the scalar's data
                                     sizeof(char)* (strlen(name.sysname))); // the length of the data in bytes
            break;


        default:
            // we should never get here - a really bad error
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_operatingSystemObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
