#!/bin/bash

POSIXLY_CORRECT=yes # Dane zadanim, ze ma byt nastavene

#DIRECTORY=$(pwd) # Priecinok, ak sa nezmeni -> aktualny pracovny

### VLASTNE FUNKCIE ###

test_funkcia()
{
	echo Ja som iba test.
}

set_directory()
{	
	if [ $# -eq 1 ] && [ -d $1 ]
	then
		echo $1
	elif [ $# -eq 2 ] && [ -d $2 ]
	then
		echo $2

	elif [ $# -eq 3 ] && [ -d $3 ]
	then
		echo $3
	else
		echo $(pwd)
	fi
}

#######################

### NASTAVENIE EDITORA ###

if [ -z ${EDITOR} ] # EDITOR nie je nastaveny
then
	# Test ci je VISUAL nastaveny
	if [ -z ${VISUAL} ] # VISUAL nie je nastaveny
	then # nastavit na "vi"
		EDITOR=vi
	else # nastavit na VISUAL
		EDITOR=$VISUAL
	fi 
fi

##########################

### KONTROLA NASTAVENIA WEDI_RC ###

if [ -z ${WEDI_RC} ] # WEDI_RC nie je nastavena
then
	# CHYBA
	echo Error! WEDI_RC is not set. 
	exit 1 # 1 == chyba??
else # WEDI_RC je nastavena
	# Ak neexistuje subor, vytvorit prazdny
	if [ ! -f $WEDI_RC ] # subor dany WEDI_RC neexistuje zatial, vytvorit prazdny
	then
		touch $WEDI_RC
	fi
fi

###################################

## NASTAVENIE DIRECTORY ##

DIRECTORY=$(set_directory $@)
echo dir is $DIRECTORY
## NASTAVENIE DIRECTORY ##


### SPRACOVANIE ARGUMENTOV ###

# Ziadne argumenty
if [ $# -eq 0 ]
then
	# Neboli zadane ziadne argumenty.
	echo 0 arg
	## VYBER NAPOSLEDY UPRAVOVANY Z DIR ##

	######################################

	## EDITUJ TEN SUBOR ##

	######################

# Nejake argumenty
else

	##################################
	
	# $1 je subor
	if [ -f $1 ]
	then
		echo edit file
		## EDITOVANIE SUBORU ##		
		test_funkcia
		#######################

	# $1 je priecinok
	elif [ $# -eq 1 ] && [ -d $1 ]
    	then 
		#DIRECTORY=$1
		echo 1args dir
		## VYBER NAPOSLEDY UPRAVOVANY ##

		################################

		## EDITUJ TEN SUBOR ##

		######################

	# prepinac -m
	elif [ $1 == "-m" ]
	then
		echo -m
		## VYBER NAJCASTEJSIE EDITOVANY ##

		##################################

		## EDITUJ TEN SUBOR ##

		######################

	# prepinac -l	
	elif [ $1 == "-l" ]
	then
		echo -l
		# Zobrazi zoznam adresarov, ktore boli v priecinku editovane

		## VYPIS ZOZNAM EDITOVANYCH SUBOROV ##

		######################################

	# prepinac -b	
	elif [ $1 == "-b" ] && [ $# -ge 2 ]
	then
		echo -b
		# Zobrazi zoznam adresarov, ktore boli v priecinku editovane pred datumom
		
		## VYPIS ZOZNAM SUBOROV EDITOVANYCH PRED DATUMOM ##

		###################################################

	# prepinac -a	
	elif [ $1 == "-a" ] && [ $# -ge 2 ]
	then
		echo -a
		# Zobrazi zoznam adresarov, ktore boli v priecinku editovane po datume

		## VYPIS ZOZNAM SUBOROV EDITOVANYCH PO DATUME ##

		################################################
	else
		echo Niekde je chyba v argumentoch	
	fi
fi

##############################
