# Generated by Django 2.2.6 on 2019-12-02 08:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id_facility', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('deadline', models.TimeField()),
                ('max_ordered_meals', models.IntegerField(default=1)),
                ('image', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=320, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.CharField(max_length=100, null=True)),
                ('diet_type', models.CharField(choices=[('n', 'normal'), ('v', 'vegetarian'), ('g', 'gluten-free')], default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('max_items', models.IntegerField(default=10)),
                ('type', models.CharField(choices=[('d', 'Daily'), ('s', 'Static')], default='s', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_driver', models.BooleanField(default=False)),
                ('is_operator', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=25, unique=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('role', models.CharField(choices=[('a', 'administrator'), ('o', 'operator'), ('d', 'driver'), ('v', 'visitor'), ('r', 'registered')], default='v', max_length=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food_order',
            fields=[
                ('id_food_order', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_delivered', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('o', 'ordered'), ('a', 'approved'), ('c', 'canceled'), ('d', 'delivered')], default='o', max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Approved_by', to='canteen.Person')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Delivered_by', to='canteen.Person')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canteen.Facility')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canteen.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Item')),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Menu')),
            ],
            options={
                'unique_together': {('id_menu', 'id_item')},
            },
        ),
        migrations.CreateModel(
            name='Food_order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('id_food_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Food_order')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Item')),
            ],
            options={
                'unique_together': {('id_food_order', 'id_item')},
            },
        ),
        migrations.CreateModel(
            name='Facility_menus',
            fields=[
                ('id_menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='canteen.Menu')),
                ('id_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Facility')),
            ],
        ),
    ]
