# Generated by Django 2.2.2 on 2019-12-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_assign_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
